### ISSUE TITLE
You cannot automatically create Steps yet.

### ISSUE THREAD

**Issue by chaochana** [danielwegener/intellij-cucumber-scala#25]
Hi,

I'm new to Cucumber Scala and when try to generate steps from feature file. I've got this error message: "You cannot automatically create Steps yet."

Please help check. Thank you very much in advance.
If you need any further information, please let me know.

The trace detail is provided:
> You cannot automatically create Steps yet.
java.lang.UnsupportedOperationException: You cannot automatically create Steps yet.
	at com.github.danielwegener.intellij.cucumber.scala.CucumberScalaExtension.getStepDefinitionCreator(CucumberScalaExtension.scala:51)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase$1.getTextFor(CucumberCreateStepFixBase.java:82)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase$1.getTextFor(CucumberCreateStepFixBase.java:65)
	at com.intellij.openapi.ui.popup.util.BaseStep.getIndexedString(BaseStep.java:48)
	at com.intellij.ui.popup.WizardPopup.shouldBeShowing(WizardPopup.java:425)
	at com.intellij.ui.popup.list.ListPopupModel.rebuildLists(ListPopupModel.java:81)
	at com.intellij.ui.popup.list.ListPopupModel.<init>(ListPopupModel.java:50)
	at com.intellij.ui.popup.list.ListPopupImpl.createContent(ListPopupImpl.java:235)
	at com.intellij.ui.popup.WizardPopup.<init>(WizardPopup.java:79)
	at com.intellij.ui.popup.WizardPopup.<init>(WizardPopup.java:70)
	at com.intellij.ui.popup.list.ListPopupImpl.<init>(ListPopupImpl.java:65)
	at com.intellij.ui.popup.list.ListPopupImpl.<init>(ListPopupImpl.java:72)
	at com.intellij.ui.popup.PopupFactoryImpl.createListPopup(PopupFactoryImpl.java:510)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase.applyFix(CucumberCreateStepFixBase.java:64)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase.applyFix(CucumberCreateStepFixBase.java:46)
	at com.intellij.codeInspection.ex.QuickFixWrapper.invoke(QuickFixWrapper.java:86)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$null$2(ShowIntentionActionsHandler.java:186)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:94)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$3(ShowIntentionActionsHandler.java:189)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:185)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.lambda$applyAction$0(IntentionListStep.java:276)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.ui.popup.AbstractPopup.lambda$null$7(AbstractPopup.java:1394)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by danielwegener** [comment]
Hi @chaochana. As the [feature overview](https://github.com/danielwegener/intellij-cucumber-scala/blob/master/README.md#features), this feature is indeed not yet implemented. It is tracked in Issue: #1

**Comment by chaochana** [comment]
Thank you for a quick response.
Looking forward to see this feature release, also Thank you in advance for this one :)

**Comment by worasit** [comment]
I am looking forward to see this features as well. Hope you guys will release this feature in the near future.
