### ISSUE TITLE
Highligt is broken

### ISSUE THREAD

**Issue by CyberGear** [danielwegener/intellij-cucumber-scala#33]
i have runner class

@RunWith(classOf[Cucumber])
@CucumberOptions(
  features = Array("src/test/resources/features"),
  glue = Array("cucumber.glue"),
  format = Array("pretty", "html:target/cucumber-report"),
  tags = Array("~@Integration","~@Ignore","~@Nightly", "~@nightly","~@NIGHTLY")
)
class RunAllTests

and steps class is defined

but lately intellij do not see steps, and cant link them to feature files

when I run tests everything is working

![image](https://user-images.githubusercontent.com/3903818/34403739-c7e85ebe-ebb2-11e7-989a-ec31a4ce398d.png)

some time ago it was fine

when i tried to create step for one of that case i got 

`You cannot automatically create Steps yet.
java.lang.UnsupportedOperationException: You cannot automatically create Steps yet.
	at com.github.danielwegener.intellij.cucumber.scala.CucumberScalaExtension.getStepDefinitionCreator(CucumberScalaExtension.scala:51)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase.askUserForFilePath(CucumberCreateStepFixBase.java:195)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase.createStepDefinitionFile(CucumberCreateStepFixBase.java:130)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase.createFileOrStepDefinition(CucumberCreateStepFixBase.java:167)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase.applyFix(CucumberCreateStepFixBase.java:108)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase.applyFix(CucumberCreateStepFixBase.java:44)
	at com.intellij.codeInspection.ex.QuickFixWrapper.invoke(QuickFixWrapper.java:88)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.invoke(IntentionActionWithTextCaching.java:181)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.b(ShowIntentionActionsHandler.java:209)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.a(ShowIntentionActionsHandler.java:213)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.b(ShowIntentionActionsHandler.java:186)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.a(ShowIntentionActionsHandler.java:185)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:184)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.a(IntentionListStep.java:293)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1431)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

Intellij version: 2017.3.2
Build: IU-173.4127.27
Cucumber for Scala version: 2017.3.0

**Comment by CyberGear** [comment]
All working, due to some data retainability problems, steps implementation class was made as object, converted back to class and moved sensitive values to objects

All good now - sorry :)

**Comment by danielwegener** [comment]
Yeah, cucumber scala dsl is a bit tricky and sometimes does not behave as expected (there is no real reason why "static"="objects" can not host glue code while it is perfectly fine in the java8 lambda java-dsl).
